# Generated by Django 3.0.1 on 2020-06-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerPlates',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Product')),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=6)),
            ],
            bases=('orders.product',),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Product')),
                ('type', models.CharField(max_length=64)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=6)),
                ('toppings_number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (5, 5)], default=0)),
            ],
            bases=('orders.product',),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Product')),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=6)),
            ],
            bases=('orders.product',),
        ),
    ]
