# Generated by Django 3.0.1 on 2020-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('size', models.CharField(choices=[('small', 'small'), ('large', 'large')], default='small', max_length=6)),
                ('toppings_number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (5, 5)], default=0)),
            ],
        ),
    ]
