# Generated by Django 3.0.1 on 2020-06-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=6),
        ),
    ]
