# Generated by Django 3.0.1 on 2020-06-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200615_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='name',
        ),
    ]
