# Generated by Django 3.0.1 on 2020-06-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_topping_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailedorder',
            name='toppings',
        ),
        migrations.AddField(
            model_name='detailedorder',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
