# Generated by Django 3.0.1 on 2020-06-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='placed',
            field=models.BooleanField(default=False),
        ),
    ]
